# Generated by Django 5.1.7 on 2025-03-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='recette',
        ),
    ]
