# Generated by Django 5.1.7 on 2025-03-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_recette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='estCorrecte',
        ),
    ]
