# Generated by Django 5.1.7 on 2025-03-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_proposition_estcorrecte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valeur_numerique', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_utilisateurs', to='questions.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropositionSelectionnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='questions.proposition')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_selectionnees', to='questions.reponseutilisateur')),
            ],
            options={
                'unique_together': {('reponse', 'proposition')},
            },
        ),
    ]
