# Generated by Django 5.2 on 2025-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_reponseutilisateur_propositionselectionnee'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propositions/'),
        ),
    ]
