# Generated by Django 5.2 on 2025-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Valeur maximale pour les questions de type slider', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Valeur minimale pour les questions de type slider', null=True),
        ),
    ]
