# Generated by Django 5.1.7 on 2025-03-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='enseignes/logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('horaires_ouverture', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('fermé', 'Fermé'), ('en_pause', 'En Pause')], default='fermé', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='active', max_length=50)),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='enseignes.enseigne')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/images/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='enseignes.categorie')),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='enseignes.enseigne')),
            ],
        ),
    ]
