# Generated by Django 5.2 on 2025-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignes', '0003_update_enseigne_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigne',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='Actif', max_length=50),
        ),
    ]
