# Generated by Django 5.2 on 2026-05-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignes', '0004_alter_enseigne_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/'),
        ),
    ]
