# Generated by Django 5.2 on 2026-05-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignes', '0005_categorie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='enseigne',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='enseigne',
        ),
        migrations.AddField(
            model_name='categorie',
            name='magasin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='enseignes.magasin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='magasin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='enseignes.magasin'),
            preserve_default=False,
        ),
    ]
