# Generated by Django 5.2 on 2026-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignes', '0005_categorie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='enseigne',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='enseigne',
        ),
        migrations.AddField(
            model_name='categorie',
            name='magasins',
            field=models.ManyToManyField(blank=True, related_name='categories', to='enseignes.magasin'),
        ),
        migrations.AddField(
            model_name='produit',
            name='magasins',
            field=models.ManyToManyField(blank=True, related_name='produits', to='enseignes.magasin'),
        ),
    ]
