# Generated by Django 5.1.7 on 2025-03-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_ingredientrecette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField()),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recipes.recette')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
