# Generated by Django 5.1.7 on 2025-03-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_etape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UstensileRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ustensile_recette', to='recipes.recette')),
                ('ustensile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes_utilisant', to='recipes.ustensile')),
            ],
        ),
    ]
