# Generated by Django 5.2 on 2025-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ustensile_ustensilerecette'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recettes/'),
        ),
    ]
