# Generated by Django 5.2 on 2025-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recette_description_recette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Brouillon', 'Brouillon'), ('Inactif', 'Inactif')], default='Actif', max_length=20),
        ),
    ]
