# Generated by Django 5.2 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('prete', 'Prête'), ('recuperee', 'Récupérée'), ('annulee', 'Annulée')], default='en_attente', max_length=50),
        ),
    ]
